# This is a basic workflow to help you get started with Actions
name: '西大晨午检上报'
# Controls when the workflow will run
on:
  schedule:
    # Write in UTC+0!
    # For example, 07:05 everyday in UTC+8 equals 23:05 everyday in UTC+0
    - cron: '22 6,18 * * *'
  watch:
    types: started
  # Triggers the workflow on push or pull request events but only for the "main" branch
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    if: github.event.repository.owner.id == github.event.sender.id
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - run: pip install -r ./r.txt  #此处为安装依赖包
      - name: Run app
        env:
          ADDRESS: ${{ secrets.ADDRESS}}
          PASSWORD: ${{ secrets.PASSWORD}}
          EAI: ${{ secrets.EAI}}
          UU: ${{ secrets.UU }}
        run: python ./python.py
